Repository MisterAzix/hetic-leboncoin-symfony, pull requests merged in 2022-10, with the labels that each got.

#1 docs: create PR template :memo:
  .github/pull_request_template.md
Labels: documentation

#6 chore: init symfony project
  src/.env
  src/.gitignore
  src/bin/console
  src/composer.json
  src/composer.lock
  src/config/bundles.php
  src/config/packages/cache.yaml
  src/config/packages/debug.yaml
  src/config/packages/doctrine.yaml
  src/config/packages/doctrine_migrations.yaml
  src/config/packages/framework.yaml
  src/config/packages/monolog.yaml
  src/config/packages/routing.yaml
  src/config/packages/sensio_framework_extra.yaml
  src/config/packages/twig.yaml
  src/config/packages/web_profiler.yaml
  src/config/preload.php
  src/config/routes.yaml
  src/config/routes/framework.yaml
  src/config/routes/web_profiler.yaml
  src/config/services.yaml
  src/migrations/.gitignore
  src/public/index.php
  src/src/Controller/.gitignore
  src/src/Entity/.gitignore
  src/src/Kernel.php
  src/src/Repository/.gitignore
  src/symfony.lock
  src/templates/base.html.twig
Labels: enhancement

#7 docs: update readme
  README.md
Labels: documentation

#17 feat(ad): create base ad crud
  src/composer.json
  src/composer.lock
  src/config/packages/validator.yaml
  src/migrations/Version20221024162300.php
  src/src/Controller/AdController.php
  src/src/Entity/Ad.php
  src/src/Entity/User.php
  src/src/Form/AdType.php
  src/src/Repository/AdRepository.php
  src/symfony.lock
  src/templates/ad/_delete_form.html.twig
  src/templates/ad/_form.html.twig
  src/templates/ad/edit.html.twig
  src/templates/ad/index.html.twig
  src/templates/ad/new.html.twig
  src/templates/ad/show.html.twig
Labels: enhancement

#20 feat: user and authentification
  src/composer.json
  src/composer.lock
  src/config/packages/framework.yaml
  src/config/packages/security.yaml
  src/config/packages/twig.yaml
  src/src/Controller/UserController.php
  src/src/Entity/User.php
  src/src/Form/UserType.php
  src/src/Security/ApiTestAuthentificatorAuthenticator.php
  src/src/Security/EmptyAuthenticator.php
  src/templates/user/_delete_form.html.twig
  src/templates/user/_form.html.twig
  src/templates/user/edit.html.twig
  src/templates/user/index.html.twig
  src/templates/user/new.html.twig
  src/templates/user/show.html.twig
Labels: enhancement

#25 feat(ad): update form style
  src/templates/ad/_form.html.twig
  src/templates/ad/edit.html.twig
  src/templates/ad/index.html.twig
  src/templates/ad/new.html.twig
  src/templates/ad/show.html.twig
Labels: enhancement

#35 feat(ad): update fixtures to include images
  src/public/images/nike_air_force_1.jpg
  src/src/Factory/AdFactory.php
  src/src/Factory/Template_images/blue_product.png
  src/src/Factory/Template_images/dark_blue_product.png
  src/src/Factory/Template_images/green_product.png
  src/src/Factory/Template_images/orange_product.png
  src/src/Factory/Template_images/pink_product.png
  src/src/Factory/Template_images/purple_product.png
  src/src/Factory/Template_images/red_product.png
  src/src/Factory/Template_images/yellow_product.png
  src/src/Service/UploadHelper.php
Labels: enhancement

#49 feat(ad): adding tag to ad
  src/src/Controller/AdController.php
  src/src/Form/AdType.php
  src/templates/ad/_form.html.twig
  src/templates/ad/show.html.twig
  src/templates/partials/_card.html.twig
Labels: enhancement

#51 fix(front): footer display
  src/templates/base.html.twig
  src/templates/partials/_footer.html.twig
Labels: bug
